# Generated by Django 5.2.1 on 2025-05-12 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='allowed_subscription_tiers',
            field=models.TextField(blank=True, default='', help_text='Comma-separated list of subscription tiers that can view this post'),
        ),
    ]
